export type TerrainCell = 'G' | 'T' | 'R';

export interface Point {
  x: number;
  y: number;
}

// G = grass: cỏ, được đặt tháp
// T = tree/rock: cây/đá, không đặt tháp
// R = road: đường, quái đi được, không đặt tháp
const RAW_MAP_GRID = `
TTTTTTTTTTTTTTTTTTTGGGGGGTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTRRRRRRTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTGGRRRRRRRRRGGGTTTTTTTTTGGGGGGGGGTTTTTTTTTTTTT
TTTTTTTTTTTTTTTGRRGGGGGGRRGGGTGGTTTTTTRRRRRRRGGTTTTTTTTTTTTT
TTTTRRTTTTTTTTGRRGGTTTTGRRGGTTTTTTTTRRRRRRRRRRGTTTTGGGGGGTTT
TTTTRRTTTTTTTTGRRGGTTTTGRRGGTTTTTTTTRRGGGGGGRRGTTTGRRRRRGTTT
TTTTRRRGGGGGGGGRRGGTTTTGRRGGRTTTTTGRRGGGGGGGRRGTTGRRTTTTRGGT
TTTTRRRRGGGGRRRRRGGGGGGGRRGRRTTTTTGRRGGGGGGGRRGTTGRGTTTRRGGT
TTTTTGRRRRRRRRRRRRGGGGGGRRRRRGGGRRRRRGGGGGTGRRRGGGRGGGGGRGGT
TTTTTTGRRRRRGGGGRRGGGGGGGRRRRGRRRRRRRRGGGGTTGRRRRRRRRRRRRGGT
TTTTTTTGGGGGTTTGRRRRRGGTTTTGRRRGGGGGRRRGTTTTTGGGGGGGGGGGGTTT
TTTTTTTTGGTTTTTGRRRRRGGTTTTGRRGGGGGGGRRGTTTTTGGGGGGTTGGGGTTT
TTTTTTTTTTTTTTTGRRRTTTTTTTTGRRGGTTTTGRRGTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTGRRRTTTTTTTTGRRGGTTTTGRRGTTTTTTTTTTTTTTTTTTTT
TTTTRRRRRGGGGGGGRRRRRTTRRRRRRRRRGGTTGRRGGGGGGGGTTTTTTTTTTTTT
TTTTRGGGRRGGGGGGRRRRRTTRRRRTTTGRRGTTGRRRRRRRRGGTTTTTTTTTTTTT
TTGRRGTTGRRGGGGRRRRRRRRRRRGTTTGGRRGGRRRRRRRRRRRGGTTTTTTTTTTT
TTGRRRTTTRRGGGRRRRRRRRRRRRRGTTGGRRRRRRGGGGGGGRRRGTTTTTTTTTTT
TTGRRRTTTTRRRRRRGTTTTTTTTRRRGGRRRGTTTTTTTTGGGGRRGGGGGGGGGTTT
TTGRRTTTTTRRRTRGGTTTTTTTTGRRRRRGGTTTTTTTTTGGGGRRGGGGGGGGGTTT
TTGRRGGGGRRGTTRRRTTTTTTTTGGGRRRGTTTTTTTTTTGGGRRRGGGGGGGTTTTT
TTTRRRRRRRGTTTRRRTTTTTTTTGGGRRGTTTTTTTTGGGRRRRRRGGGGGGGTTTTT
TTTTRGGGGGTTTTTRRGGGGTTGGGGGGRRGTTTTTTGRRRRRRRRRRRGGGGGTTTTT
TTTTRGGGGGTTTTTRRRRRGGTGGRGGGRRGTTTTTGRRRGGTTTTTTRRGGGGTTTTT
TTTTTTTTTTTTTTTGGGGRRGGTGRGGGRRGTTTTGGRRGGTTTTTTTGRRGTTTTTTT
TTTTTTTTTTTTTTTGGTGGRRRGGRRRRRGGTTTTGGRRGGTTTTTTTGRRGTTTTTTT
TTTTTTTTTTTTTTTTTTTGGRRRRRRRRRRRRRRRRRRGGGTTTTTTTGRRGTTTTTTT
TTTTTTTTTTTTTTTTTTTGGRRRGGGGGGRRRRRRRRGGGGTTTTTTTRRGGTTTTTTT
TTTTTTTTTTTTTTTTTTTGGRRGGGGGGGGGTTTTTTTTTTTTTTTTTRRGRTTTTTTT
TTTTTTTTTTTTTTTTTTTGRRRGGGGGGGGGTTTTTTTTTTTTTTTTTRRRGTTTTTTT
TTTTTTTTTTTTTTGGGGGRRRGGGGGGGTTTTTTTTTTTTTTTTTTTTRRRRGGRRTTT
TTTTTTTTTTTTTGRRRRRRRRGGGGGGGTTTTTTTTTTTTTTTTTTTTRRRRRRRRTTT
TTTTGGTTTTTTGRRGGGGGRRRGGGGGGTTTTTTTTTTTTTTTTTTTTTTTTTTRRRRR
TTTTGGTTTTTTGRGGTTTTGRRRRGGGGTTTTTTTTTTTTTTTTTTTTTTTTTTGRRRR
TTTTTTTTTTTTGRGTTTTTTTGRRRRGGTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTR
TTTTTTTTTTTTGRRTTTTTTTTGGRRRGTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTG
`;

const RAW_ROWS = RAW_MAP_GRID.trim().split('\n').map((line) => line.trim());

export const GRID_ROWS = RAW_ROWS.length;
export const GRID_COLS = Math.max(...RAW_ROWS.map((row) => row.length));

export const MAP_GRID = RAW_ROWS.map((row) => row.padEnd(GRID_COLS, 'T')) as readonly string[];

export function percentToGrid(xPercent: number, yPercent: number) {
  const col = Math.max(
    0,
    Math.min(GRID_COLS - 1, Math.floor((xPercent / 100) * GRID_COLS))
  );

  const row = Math.max(
    0,
    Math.min(GRID_ROWS - 1, Math.floor((yPercent / 100) * GRID_ROWS))
  );

  return { row, col };
}

export function gridToPercent(row: number, col: number): Point {
  return {
    x: ((col + 0.5) / GRID_COLS) * 100,
    y: ((row + 0.5) / GRID_ROWS) * 100,
  };
}
export function getTerrainAtGrid(row: number, col: number): TerrainCell {
  const safeRow = Math.max(0, Math.min(GRID_ROWS - 1, row));
  const safeCol = Math.max(0, Math.min(GRID_COLS - 1, col));

  const cell = MAP_GRID[safeRow][safeCol];

  if (cell === 'G' || cell === 'T' || cell === 'R') {
    return cell;
  }

  return 'T';
}

export function getTerrainAtPercent(xPercent: number, yPercent: number): TerrainCell {
  const { row, col } = percentToGrid(xPercent, yPercent);
  return getTerrainAtGrid(row, col);
}

export function isTowerPlaceableAtPercent(xPercent: number, yPercent: number) {
  return getTerrainAtPercent(xPercent, yPercent) === 'G';
}

export function getTerrainMessage(cell: TerrainCell) {
  if (cell === 'R') return 'Không thể đặt tháp trên đường đi!';
  if (cell === 'T') return 'Không thể đặt tháp lên cây/đá!';
  return '';
}
